apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-controller
  namespace: ingress-nginx
data:
  proxy-cache-path: "/data/nginx/cache levels=1:2 keys_zone=mycache:10m max_size=100m inactive=60m use_temp_path=off;"
