apiVersion: apps/v1
kind: Deployment
metadata:
  name:  private-image-regcred-dep
  namespace: default
  labels:
    app:  private-image-dep
spec:
  selector:
    matchLabels:
      app: private-image-dep
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  private-image-dep
    spec:
      containers:
      - name:  private-image-dep
        image:  denizyoutube/private_image:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  80
          name:  private
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always