apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: prod-
# nameSuffix: "-001"
namespace: prod

patches:
- path: prod-service.yaml
- path: prod-deployment.yaml
- path: prod-namespace.yaml

  #images:
  #- name: nginx:latest
  # newName: denizturkmen/python
  # newTag: "env1"