##################################################
# RollingUpdate Service - Manifest
##################################################
apiVersion: v1
kind: Service
metadata:
  name: roolingupdate-test
  namespace: default
spec:
  selector:
    app: roolingupdate
  type: NodePort
  ports:
  - name: roolingupdate-dep-test
    protocol: TCP
    port: 80
    targetPort: 5000 
    nodePort: 32425