---
# Kustomize Feature List
# https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/#kustomize-feature-list

namespace: prod
namePrefix: prod-

resources:
- ../../base/prod
- namespace.yaml

patches:
- path: namespace.yaml

secretGenerator:
- name: more-secret
  literals:
  - KEY1=newsecretvalue1
  - KEY2=newsecretvalue2
  - KEY3=anothersecretvalue
