apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ui-ing
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: denizturkmen.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-ui
            port:
              number: 80

              spec:
  containers:
    - name: controller
      args:
        - /nginx-ingress-controller
        - --enable-annotation-validation=false
        - --allow-snippet-annotations=true
      volumes:
      - name: nginx-cache-config
        configMap:
          name: ingress-nginx-controller
