apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default  # Change this if needed
  labels:
    app: nginx
data:
  nginx.conf: |
    server {
        listen 80;
        server_name denizturkmen.com;

        set $proxy_pass_url https://localhost:8080;

        ssl_session_cache builtin:1000 shared:SSL:10m;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
        ssl_prefer_server_ciphers on;

        location / {
            proxy_set_header        Host $host;
            proxy_set_header        X-Real-IP $remote_addr;
            proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header        X-Forwarded-Proto $scheme;
            proxy_pass              http://localhost:8080;
            proxy_redirect          $proxy_pass_url/ /;
        }

        # Cache CSS and Images
        location ~* \.(?:css|js|jpg|jpeg|png|gif|ico|woff2|woff|ttf|svg|webp)$ {
            expires 30d;
            proxy_cache STATIC;
            proxy_cache_valid 200 301 302 30d;
            proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
            proxy_pass http://localhost:8080;
            add_header X-Cache-Status $upstream_cache_status;
        }
    }
