apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default  
  labels:
    app: web-ui
data:
  nginx.conf: |
    worker_processes auto;

    events {
    worker_connections 1024;
    }

    http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    # Define proxy cache path
    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=STATIC:10m inactive=60m use_temp_path=off;

    server {
        listen 80;
        server_name denizturkmen.com;

        # Use Kubernetes Service instead of localhost
        set $proxy_pass_url http://web-ui.default.svc.cluster.local:80;

        location / {
            proxy_set_header        Host $host;
            proxy_set_header        X-Real-IP $remote_addr;
            proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header        X-Forwarded-Proto $scheme;
            proxy_pass              $proxy_pass_url;
            proxy_redirect          off;
        }

        # Cache CSS and Images
        location ~* \.(?:css|js|jpg|jpeg|png|gif|ico|woff2|woff|ttf|svg|webp)$ {
            expires 30d;
            proxy_cache STATIC;
            proxy_cache_valid 200 301 302 30d;
            proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
            proxy_pass $proxy_pass_url;
            add_header X-Cache-Status $upstream_cache_status;
        }
      }
    }

