---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: np5
  namespace: b
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: a
          podSelector:
            matchLabels:
              run: pod-c
