apiVersion: v1
kind: Secret
metadata:
  name: heketi-secret
  namespace: default
type: "kubernetes.io/glusterfs"
data:
  # echo -n "ivd7dfORN7QNeKVO" | base64
  key: aXZkN2RmT1JON1FOZUtWTw==
type: kubernetes.io/glusterfs
