apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: dev-
nameSuffix: "-001"
namespace: dev

patches:
- path: dev-service.yaml
- path: dev-deployment.yaml

  #images:
  #- name: nginx:latest
  # newName: denizturkmen/python
  # newTag: "env1"