---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: nginx
        volumeMounts:
        - name: credentials
          mountPath: /etc/config
      volumes:
      - name: credentials
        configMap:
          name: credentials