##################################################
# Horizontal Pod Auto Scaling - v1 - Manifest
##################################################
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: horizontal-auto-scaling-1
  namespace: hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hpa
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 20
---
##################################################
# Horizontal Pod Auto Scaling - v2- Manifest
##################################################
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hpa
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
