##################################################
# Horizontal Pod Auto Scaling 3 - Manifest
##################################################
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: horizontal-auto-scaling-3
  namespace: hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hpa
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 40
      policies:
      - type: Percent
        value: 20
        periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 40
      policies:
      - type: Percent
        value: 20
        periodSeconds: 20
      - type: Pods
        value: 5
        periodSeconds: 20
      selectPolicy: Max
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 30