apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-name # HorizontalPodAutoscaler name
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment # Scale k8s object name
    name: deployment-name 
  minReplicas: 1 # Min pod replica
  maxReplicas: 7 # Max pod replica
  behavior:
    scaleDown: # CPU or RAM scale as utilization 
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent 
        value: 10
        periodSeconds: 1800 # Check period sn
      - type: Pods
        value: 1
        periodSeconds: 1800
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 25
        periodSeconds: 50
      - type: Pods
        value: 1
        periodSeconds: 50
      selectPolicy: Max