apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-name # HorizontalPodAutoscaler name
spec:
  scaleTargetRef: # Autoscale settings related to the target pod to be used
    apiVersion: apps/v1
    kind: Deployment # Scale k8s object name
    name: deployment-name 
  minReplicas: 1 # at least how many pods will work
  maxReplicas: 7 # at most how many pods will work
  behavior:
    scaleDown: # CPU or RAM scale as utilization 
      stabilizationWindowSeconds: 300 # Used to determine at least how many seconds the system will remain stable
      policies: # Scale politics
      - type: Percent 
        value: 10
        periodSeconds: 1800 # Check period sn
      - type: Pods
        value: 1
        periodSeconds: 1800
    scaleUp:
      stabilizationWindowSeconds: 0
      policies: # Scale politics
      - type: Percent
        value: 25 
        periodSeconds: 25
      - type: Pods
        value: 1
        periodSeconds: 25
      selectPolicy: Max