##################################################
# BlueGree Service - Manifest
##################################################
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: default
spec:
  selector:
    app: web-app
    strategies: blue
  type: ClusterIP
  ports:
  - name: web-svc
    protocol: TCP
    port: 80
    targetPort: 80
    
